### ISSUE TITLE
Wordpress plugin

### ISSUE THREAD

**Issue by gioppi** [WarriorRocker/angular-xo-core#1]
I tryed to install the pluginin wp, but I got this error:
Parse error: syntax error, unexpected 'version' (T_STRING) in .....t/wp-content/plugins/xo-for-angular/assets/svg/angular-xo-white.svg  on line 1

Best wishes for your project, it looks great!

**Comment by WarriorRocker** [comment]
Have you installed this through the WordPress plugin repository or by uploading the files directly from github?

Can you make sure that the folder is named "xo-for-angular" as well?

Is it possible to get the full output of the error_log for the above?

Thanks!

**Comment by gioppi** [comment]
Hi. Thanks for the response.

I installed throuth WP plugin reposity. It installed the app, but when I 
activated it I got the error


Angular theme development in WordPress with templates and a powerful API.

Versione 1.0.1 | Di Travis Brown <http://www.xodustech.com> | Visualizza 
i dettagli 
<https://wp-tutor.it/wp-admin/plugin-install.php?tab=plugin-information&plugin=xo-for-angular&TB_iframe=true&width=600&height=550>



*Parse error*: syntax error, unexpected 'version' (T_STRING) in 
*/home/qartapol/public_html/wp-tutor.it/wp-content/plugins/xo-for-angular/assets/svg/angular-xo-white.svg* 
on line *1*




Best regards
Giovanni



Il 08/03/2019 23:37, WarriorRocker ha scritto:

**Comment by WarriorRocker** [comment]
Thanks for this!

After some digging I found a similar issue documented here: https://sheelahb.com/blog/how-to-get-php-to-play-nicely-with-svg-files/

I have put in the suggested fix which hopefully addresses this issue.

You may need to delete the plugin and install it fresh, ensure that you get 1.0.2.

Let me know if that gets it going for you!

**Comment by gioppi** [comment]
thanks, i try!

Il 09/03/2019 13:55, WarriorRocker ha scritto:

**Comment by gioppi** [comment]
I just uptdated it in wp and it looks working.

Wonderfull!.

Now I will try to use it.

Thank you

Giovanni

Il 09/03/2019 13:55, WarriorRocker ha scritto:

**Comment by WarriorRocker** [comment]
Glad to hear it. Closing this issue unless it comes up again.

Thanks!

**Comment by gioppi** [comment]
I tryed to load the

https://github.com/WarriorRocker/angular-xo-material

as a theme in worpdress

but see

https://wp-tutor.it/

best regards

g

Il 09/03/2019 15:00, WarriorRocker ha scritto:

**Comment by WarriorRocker** [comment]
Can you open a separate issue with more details? I am not sure I understand the problem.

Thanks.

**Comment by WarriorRocker** [comment]
I see, "Unable to render index.".

This is most likely that you need to compile the src app so there is a /dist folder with the index.html and other assets inside.

From the theme folder /wp-content/themes/angular-xo-material, run:

$ npm install
$ npm run build

Assuming you have node and the angular cli already installed.

I will only keep the source files in the repository. If I am eventually able to add the theme to the WordPress repository I would add the compiled version using: $ npm run deploy.

**Comment by gioppi** [comment]
solved. thanks
