### ISSUE TITLE
Allow Angular Peer Dependency of 8

### ISSUE THREAD

**Issue by pathurs** [WarriorRocker/angular-xo-core#4]
```
npm WARN angular-xo@0.2.1 requires a peer of @angular/common@^6.0.0-rc.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-xo@0.2.1 requires a peer of @angular/core@^6.0.0-rc.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-xo@0.2.1 requires a peer of @angular/platform-browser@^6.0.0-rc.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-xo@0.2.1 requires a peer of @angular/router@^6.0.0-rc.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.
```

I haven't test of this works as of yet, however I believe it should.

**Comment by mirr** [comment]
Hey man, does angular 8 running without any issue?

**Comment by pathurs** [comment]
It has been working from what I can tell in my usage.

**Comment by WarriorRocker** [comment]
I have updated the [Angular Xo Material](https://github.com/WarriorRocker/angular-xo-material) theme and [Angular Xo](https://github.com/WarriorRocker/angular-xo-node) module to the latest version of Angular 8.

As an update proceedure it is recommended to delete the node_modules in your theme folder, update the package.json dependencies as indicated in the Angular Xo Material theme and do an `npm install`. There were no other code changes necessary within the theme itself.

Let me know if there are any issues at https://github.com/WarriorRocker/angular-xo-material/issues
