### ISSUE TITLE
Project already dead ?

### ISSUE THREAD

**Issue by samfrach** [WarriorRocker/angular-xo-core#6]
Hello,

Project is still in Angular 7 ... is it dead ?

Where can I find a working example ? 

thanks a lot...

**Comment by mirr** [comment]
I guess the author does not need to regularly update this repo. Anyway, a working theme is https://github.com/WarriorRocker/angular-xo-material.
Download and install that. And make sure to follow the guide from the website.

I based the wp them we created on that theme.

**Comment by WarriorRocker** [comment]
Hi,

This project is far from dead and plan on making many updates and improvements in the near future.

Let me know any suggestions.

Actually on the fence about a few things. Mainly considering bringing the Xo API back into the WP Rest API. At the time I had started this project, an original version using AngularJS the WP Rest API was simply not capable of serving a real single page application experience. Seems this is still mostly the case with the posts APIs being extremely limited.

@mirr Would you be willing to share some details about how you make use of this plugin? Any feedback is helpful in knowing where to apply focus and for the consideration of potential future breaking changes.

In regards to Angular 8, I have been testing this and see no issues so far, expect these updates soon.

**Comment by WarriorRocker** [comment]
As a follow-up to this, I have updated the [Angular Xo Material](https://github.com/WarriorRocker/angular-xo-material) theme and [Angular Xo](https://github.com/WarriorRocker/angular-xo-node) module to the latest version of Angular 8.

As an update proceedure it is recommended to delete the node_modules in your theme folder, update the package.json dependencies as indicated in the Angular Xo Material theme and do an `npm install`. There were no other code changes necessary within the theme itself.

Let me know if there are any issues at https://github.com/WarriorRocker/angular-xo-material/issues

**Comment by ServiceSector** [comment]
> Hi,
> 
> This project is far from dead and plan on making many updates and improvements in the near future.
> 
> Let me know any suggestions.
> 
> Actually on the fence about a few things. Mainly considering bringing the Xo API back into the WP Rest API. At the time I had started this project, an original version using AngularJS the WP Rest API was simply not capable of serving a real single page application experience. Seems this is still mostly the case with the posts APIs being extremely limited.
> 
> @mirr Would you be willing to share some details about how you make use of this plugin? Any feedback is helpful in knowing where to apply focus and for the consideration of potential future breaking changes.
> 
> In regards to Angular 8, I have been testing this and see no issues so far, expect these updates soon.

Hi, could you give devs like us an idea of the roadmap for this project? Sounds promising. 
<hr>

If you don't mind, I'd like to pick your brain regarding the working philosophy on the project at this point in time (2/3/2020, Angular 9+). Concerning the following lines from docs: 

**"Use WordPress to manage content for pages and posts and let Xo generate your routes dynamically."** 
In the sense that it may serve as a "two-way binding" between angular and wp, so to speak? As in, right as angular is loading the view, it fills the default element _<xo-api>_ with the _content_ of the wp page? This sounds interesting and useful for some use cases, could even become an independent CMS for bloggers or something like that. About routing, considering angular seems to work with routes quite nicely, would this function simply replace the native angular routing? This may be troubling I think.

**Use the Xo API to get pages, posts, menus, options, and more in your Angular app.**
These are easy enough to do within a standalone angular project, via a simple wp-json call, not sure what the use would be here. Even the last point would be easy to do with angular alone.

**Run locally using ng serve for rapid development of new features and updates.**
On the opposite spectrum of making it easy for bloggers & publishers or similar to get the look and feel of angular without the technicalities, there is the aspect of making it easier for developers & corporations to develop code, I think this point needs much more clarification as it has a lot of potential, as all things that speed up dev time.

**Deploy for production using ng build and then distribute your theme with or without the source code.**
Not sure what this means, I read up other issues on this repo related to this, needs a bit more clarification in my opinion. Step by step video guides usually do the trick, even if silent.

Also, a potential breaking point for this may be the fork between node.js servers & php-based CMS like wp, curious to know you or others feel about this or anything else I wrote above
